# /myscripts/dhcpd.conf
failover peer "anti-bongcloud" {
    secondary;                  # RuyLopez server secondary
    address 10.49.41.131;       # Alamat IP RuyLopez
    port 647;                   # Port komunikasi failover
    peer address 10.49.41.130;  # Alamat IP Ponziani
    peer port 647;              # Port komunikasi Ponziani
}

subnet 10.49.0.0 netmask 255.255.224.0 {
    option routers 10.49.0.1;
    option broadcast-address 10.49.31.255;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;

    pool {
        failover peer "anti-bongcloud";
        range 10.49.0.10 10.49.31.254;
    }
}

subnet 10.49.32.0 netmask 255.255.248.0 {
    option routers 10.49.32.1;
    option broadcast-address 10.49.39.255;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;

    pool {
        failover peer "anti-bongcloud";
        range 10.49.32.10 10.49.39.254;
    }
}

subnet 10.49.40.0 netmask 255.255.255.0 {
    option routers 10.49.40.1;
    option broadcast-address 10.49.40.255;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;

    pool {
        failover peer "anti-bongcloud";
        range 10.49.40.10 10.49.40.254;
    }

    host Slav {
        hardware ethernet 02:42:a6:21:e1:00;
        fixed-address 10.49.40.2;
    }
}

subnet 10.49.41.0 netmask 255.255.255.128 {
    option routers 10.49.41.1;
    option broadcast-address 10.49.41.127;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;
    pool {
        failover peer "anti-bongcloud";
        range 10.49.41.10 10.49.41.126;
    }

    host Sicillian {
        hardware ethernet 02:42:8c:44:92:00;
        fixed-address 10.49.41.2;
    }
}

subnet 10.49.41.128 netmask 255.255.255.192 {
    option routers 10.49.41.129;
    option broadcast-address 10.49.41.191;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;
    pool {
        failover peer "anti-bongcloud";
        range 10.49.41.140 10.49.41.190;
    }
}

subnet 10.49.41.192 netmask 255.255.255.240 {
    option routers 10.49.41.193;
    option broadcast-address 10.49.41.207;
    option domain-name-servers 10.49.41.194, 10.49.41.195, 8.8.8.8;
    default-lease-time 600;
    max-lease-time 7200;
    pool {
        failover peer "anti-bongcloud";
        range 10.49.41.196 10.49.41.206;
    }
}
