options {
    directory "/myscripts/dns";
    listen-on { any; };
    allow-query { any; };
    allow-transfer { 10.49.41.195; }; # transfer ke slave (Alekhine)
    dnssec-validation no;
};

zone "parkov.com" IN {
    type master;
    file "db.parkov.com";
};

zone paskarov.com IN {
    type master;
    file "db.paskarov.com";
};

zone "openings.com" IN {
    type master;
    file "db.openings.com";
};