user www-data;
worker_processes auto;
worker_cpu_affinity auto;
pid /tmp/nginx.pid;
error_log /tmp/error.log;

events { worker_connections 768; }

http {
    log_format  no6 '[$time_local] Jarkom Node Gustave Access from $remote_addr using method "$request" returned status $status with $body_bytes_sent bytes sent in $request_time seconds';
    
    server {
        listen 8888;
        listen 8080;
        server_name gustave33.com;

        access_log /tmp/access.log no6;
        root /myscripts/myweb;
        index profile_gustave.html;
        
        location / {
        try_files $uri $uri/ =404;
        }
    }

    server {
        listen 8200;
        server_name gustave33.com;

        access_log /tmp/access.log no6;
        root /myscripts/myweb;
        index info.html;
        
        location / {
        try_files $uri $uri/ =404;
        }
    }
}
