user www-data;
worker_processes auto;
worker_cpu_affinity auto;
pid /tmp/nginx.pid;
error_log /tmp/error.log;

events { worker_connections 768; }

http {
    upstream roundrobinx {
        server 10.49.2.1:8000;
        server 10.49.2.2:8100;
        server 10.49.2.3:8200;
    }

    log_format  no6 '[$time_local] Jarkom Node Alicia Access from $remote_addr using method "$request" returned status $status with $body_bytes_sent bytes sent in $request_time seconds';
    
    server {
        listen 80;
        server_name expeditioners.com;
        access_log /tmp/access.log no6;

        location = / {
            proxy_pass http://roundrobinx/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /profil_lune {
            proxy_pass http://10.49.2.1:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /profil_sciel {
            proxy_pass http://10.49.2.2:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /profil_gustave {
            proxy_pass http://10.49.2.3:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            rewrite ^ / last;
        }
    }
}