options {
      directory "/myscripts/dns";
      listen-on { any; };
      allow-query { any; };
      dnssec-validation no;
};

zone "lune33.com" {
      type slave;
      file "db.lune33";
      masters { 10.49.3.1; };  # IP master (Renoir)
};

zone "sciel33.com" {
      type slave;
      file "db.sciel33";
      masters { 10.49.3.1; };
};

zone "gustave33.com" {
      type slave;
      file "db.gustave33";
      masters { 10.49.3.1; };
};

zone "2.49.10.in-addr.arpa" {
    type slave;
    file "db.2.49.10.in-addr.arpa";
    masters { 10.49.3.1; };
};

zone "expedition.gustave33.com" {
    type master;
    file "db.expedition.gustave33";
};

zone "expeditioners.com" {
      type slave;
      file "db.expeditioners";
      masters { 10.49.3.1; };
};